{{- if .Values.memgraph.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: memgraph-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "darwin.labels" . | nindent 4 }}
    app.kubernetes.io/component: memgraph
type: Opaque
stringData:
  MEMGRAPH_ENTERPRISE_LICENSE: ""
  MEMGRAPH_ORGANIZATION_NAME: ""
{{- end }}
