# BlackBoard/helm/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-redis
  labels:
    {{- include "darwin.labels" . | nindent 4 }}
type: Opaque
stringData:
  password: "{{ .Values.redis.password }}"
---
{{- if .Values.memgraph.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-memgraph
  labels:
    {{- include "darwin.memgraphLabels" . | nindent 4 }}
type: Opaque
stringData:
  username: "{{ .Values.memgraph.auth.username }}"
  password: "{{ .Values.memgraph.auth.password }}"
{{- end }}
