# BlackBoard/helm/templates/serviceaccount.yaml
# ServiceAccount for K8s metrics API access
{{- if or .Values.observer.enabled .Values.slackAccess.enabled .Values.ephemeralAgents.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-brain
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "darwin.labels" . | nindent 4 }}
{{- end }}
