# BlackBoard/src/agents/tool_router.py
# @ai-rules:
# 1. [Pattern]: Async handlers. Registry-driven dispatch. No Brain import except TYPE_CHECKING.
# 2. [Constraint]: Handlers are called within per-event asyncio.Lock — MUST NOT re-acquire.
# 3. [Pattern]: ToolContext is a Brain-level singleton (one per Brain instance). Methods take eid.
# 4. [Pattern]: HandlerFn returns True = re-invoke LLM immediately. False = stop loop iteration.
# 5. [Gotcha]: _run_agent_task and _close_and_broadcast stay on Brain — injected as callbacks.
# 6. [Pattern]: HANDLER_REGISTRY maps tool name -> handler coroutine. Thin dispatcher does lookup.
"""BrainToolRouter: registry-driven tool handler dispatch with ToolContext DI."""
from __future__ import annotations

from typing import TYPE_CHECKING, Awaitable, Callable, Protocol, runtime_checkable

if TYPE_CHECKING:
    from ..models import ConversationTurn, EventDocument
    from ..state.blackboard import BlackboardState

# ---------------------------------------------------------------------------
# HandlerFn type alias
# ---------------------------------------------------------------------------
HandlerFn = Callable[
    ["ToolContext", str, dict, "list[dict] | None"],
    Awaitable[bool],
]


# ---------------------------------------------------------------------------
# Narrow Ports — typed return values for ToolContext accessors
# ---------------------------------------------------------------------------
class StateWatcherPort(Protocol):
    """Narrow port for StateWatcher — handlers only call register()."""
    def register(self, spec: object) -> bool: ...


class IdleTimeoutPort(Protocol):
    """Narrow port for IdleTimeoutManager — handlers only call schedule()."""
    def schedule(self, event_id: str, warning_sec: int | None = None) -> None: ...


class IncidentAdapterPort(Protocol):
    """Narrow port for incident adapters."""
    async def create_incident(self, fields: dict) -> dict: ...
    async def list_incidents(self, label_filter: str = "") -> list[dict]: ...
    async def search_open_incidents(self) -> list[dict]: ...
    async def add_comment(self, issue_key: str, body_markdown: str) -> dict: ...


# ---------------------------------------------------------------------------
# ToolContext: mutable Protocol — Brain singleton, methods take event_id
# ---------------------------------------------------------------------------
@runtime_checkable
class ToolContext(Protocol):
    """Dependency-injection surface for tool handlers.

    Brain constructs one instance at startup, binding its own state dicts
    and callbacks. Handlers receive this across all events.
    """

    # === Wait states ===
    def mark_waiting_for_user(self, eid: str) -> None: ...
    def clear_waiting_for_user(self, eid: str) -> None: ...
    def is_waiting_for_user(self, eid: str) -> bool: ...
    def mark_waiting_for_agent(self, eid: str, agent: str, wait_turn: int) -> None: ...
    def clear_waiting_for_agent(self, eid: str) -> None: ...
    def is_waiting_for_agent(self, eid: str) -> bool: ...

    # === Agent dispatch ===
    def is_task_running(self, eid: str) -> bool: ...
    def get_routing_depth(self, eid: str) -> int: ...
    def increment_routing_depth(self, eid: str) -> int: ...
    def is_dispatch_locked(self) -> bool: ...
    def get_active_agent_for_event(self, eid: str) -> str | None: ...
    def get_agent_instance(self, name: str) -> object | None: ...

    # === Environment ===
    def get_ws_mode(self) -> str: ...

    # === Subscriptions ===
    def get_state_watcher(self) -> StateWatcherPort | None: ...
    def get_cycle_id(self, eid: str) -> str: ...
    def cancel_stale_subscriptions(self, eid: str, cycle: str) -> None: ...

    # === JARVIS ===
    def mark_jarvis_wait(self, eid: str, timestamp: float) -> None: ...
    def clear_jarvis_wait(self, eid: str) -> None: ...
    def has_jarvis_waiters(self) -> bool: ...
    def get_active_meta_event_id(self) -> str | None: ...
    def is_in_hold_watch(self, eid: str) -> bool: ...
    def get_jarvis_wait_count(self, eid: str) -> int: ...
    def increment_jarvis_wait_count(self, eid: str) -> int: ...
    def set_hold_watch(self, eid: str, deferred_snapshot: frozenset) -> None: ...
    def set_hold_watch_park_time(self, eid: str) -> None: ...
    # === Dedup/cache ===
    def has_incident_been_created(self, eid: str) -> bool: ...
    def mark_incident_created(self, eid: str) -> None: ...
    def get_cached_journal(self, svc: str) -> Awaitable[list[str]]: ...

    # === Timers ===
    def get_idle_timeout(self) -> IdleTimeoutPort: ...
    def get_last_processed(self, eid: str) -> float: ...
    def update_last_processed(self, eid: str) -> None: ...
    def get_conversation_timeout(self, event: "EventDocument") -> int: ...

    # === Callbacks (injected, not state) ===
    async def append_and_broadcast(
        self, event_id: str, turn: "ConversationTurn", event: "EventDocument | None" = None,
    ) -> int: ...

    async def broadcast(self, message: dict) -> None: ...

    async def emit_pulse(
        self, event_id: str, pulses: list[tuple],
    ) -> None: ...

    async def next_turn_number(self, event_id: str) -> int: ...

    async def close_and_broadcast(
        self, event_id: str, summary: str, close_reason: str | None = None,
    ) -> None: ...

    async def run_agent_task(
        self, event_id: str, agent_name: str, agent: object | None,
        task: str, event_md_path: str, routing_turn_num: int,
        mode: str = "", parallel: bool = False, effort: str = "",
    ) -> None: ...

    async def dispatch_handler(
        self, name: str, event_id: str, args: dict,
        response_parts: "list[dict] | None",
    ) -> bool: ...

    def get_blackboard(self) -> "BlackboardState": ...

    def get_slack_channel(self) -> object | None: ...

    def get_incident_adapter(self) -> IncidentAdapterPort | None: ...

    async def deliver_to_jarvis(self, event_id: str, message: str) -> None: ...

    async def stamp_event(self, event_id: str, **kwargs: object) -> None: ...

    async def record_event(self, event_type: object, data: dict, narrative: str = "") -> None: ...

    # === Constants ===
    @property
    def ephemeral_only_roles(self) -> frozenset[str]: ...


# ---------------------------------------------------------------------------
# Handler registry — populated by extraction modules (Steps 3.2-3.6)
# ---------------------------------------------------------------------------
HANDLER_REGISTRY: dict[str, HandlerFn] = {}
